Scikit Learn

An End To end scikit-learn workflow
Getting the data ready
choosing the right estimator and algorithm of our problems
fit the model and use it to make predictions on data
Evaluating a model
Improve a model
Save and load a trained model
putting it all together
    

# An End to End scikit-learn workflow

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

heart_disease=pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
#create x (features matrix)
X=heart_disease.drop("target",axis=1)

#create y (label)
Y=heart_disease["target"]

In [3]:
#choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()

#we will keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
#fit the model tto the training data
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [5]:
clf.fit(X_train,Y_train)

RandomForestClassifier()

In [6]:
#make a prediction 
import numpy as np

In [7]:
# Y_label=clf.predict(np.array([0,2,3,4]))

In [8]:
ypreds=clf.predict(X_test)

In [9]:
ypreds

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

In [10]:
Y_test

62     1
170    0
237    0
212    0
23     1
      ..
70     1
20     1
74     1
176    0
17     1
Name: target, Length: 61, dtype: int64

In [11]:
#Evaluating the model how well it predict 
clf.score(X_train,Y_train)

1.0

In [12]:
clf.score(X_test,Y_test)

0.819672131147541

In [13]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


In [14]:
print(classification_report(Y_test,ypreds))

              precision    recall  f1-score   support

           0       0.78      0.86      0.82        29
           1       0.86      0.78      0.82        32

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [15]:
print(confusion_matrix(Y_test,ypreds))

[[25  4]
 [ 7 25]]


In [16]:
print(accuracy_score(Y_test,ypreds))

0.819672131147541


In [17]:
#improve a model
#Improving by tuning various hyperparameters
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators")
    clf=RandomForestClassifier(n_estimators=i).fit(X_train,Y_train)
    print("Model accuracy on test set")
    print(f"{clf.score(X_test,Y_test)*100}%")
    print("")

Trying model with 10 estimators
Model accuracy on test set
77.04918032786885%

Trying model with 20 estimators
Model accuracy on test set
81.9672131147541%

Trying model with 30 estimators
Model accuracy on test set
77.04918032786885%

Trying model with 40 estimators
Model accuracy on test set
80.32786885245902%

Trying model with 50 estimators
Model accuracy on test set
75.40983606557377%

Trying model with 60 estimators
Model accuracy on test set
80.32786885245902%

Trying model with 70 estimators
Model accuracy on test set
78.68852459016394%

Trying model with 80 estimators
Model accuracy on test set
77.04918032786885%

Trying model with 90 estimators
Model accuracy on test set
80.32786885245902%



In [18]:
#save a model and load it 
import pickle

pickle.dump(clf,open("heart_disease_RandomForest_ModelOne.pkl","wb"))

In [19]:
#loading a saved model
loaded_model=pickle.load(open("heart_disease_RandomForest_ModelOne.pkl","rb"))
loaded_model.score(X_test,Y_test)

0.9508196721311475

# Getting our data ready to be used

# Three main things we have to do here -
1.Split the data into the features and labels (X=features and y=labels)
2.Filling also called imputing or disregarding missing values
3.Converting non-numericcal values to numerical values (also called feature encoding)

In [20]:
#features and labels
X=heart_disease.drop("target",axis=1)

In [21]:
y=heart_disease["target"]

In [22]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [23]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [24]:
#splitting the data into train and tests
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [25]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

# Making it all numerical

In [26]:
car_sales=pd.read_csv("car-sales-extended.csv")

In [27]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [28]:
len(car_sales)

1000

In [30]:
#splitting into x and y
X=car_sales.drop("Price",axis=1)

y=car_sales["Price"]


In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.ensemble import RandomForestRegressor

#getting the model
model=RandomForestRegressor()

#fitting the model
model.fit(X_train,y_train)

#checking model or running the model
model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

# Turning the string into numbers

In [35]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")

transformed_X=transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

So what we did here was we converted the columns Make,Colour and Doors into
numbers through OneHotEncoder and remainder=passthrough means we left the
remaining columns except for Make,Colour and Doors as they were before !

In [36]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

# Now we have all numerical data,so lets refit the model and see if it works

In [37]:
X_train,X_test,y_train,y_test=train_test_split(transformed_X,y,test_size=0.2)

In [38]:
from sklearn.ensemble import RandomForestRegressor

#getting the model
model=RandomForestRegressor()

#fitting the model
model.fit(X_train,y_train)

#checking model or running the model
model.score(X_test,y_test)

0.2330485230539474

# So What if there were some missing data ???
1.Fill them with some value (also known as imputation)
2.Remove the samples with missing data altogether

In [41]:
#lets work on missing data
csm=pd.read_csv("car-sales-extended-missing-data.csv")

In [42]:
csm

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [43]:
csm.isna()

Make  Colour  Odometer (KM)  Doors  Price
0    False   False          False  False  False
1    False   False          False  False  False
2    False   False          False  False  False
3    False   False          False  False  False
4    False   False          False  False  False
..     ...     ...            ...    ...    ...
995  False   False          False  False  False
996   True   False          False  False  False
997  False   False          False  False  False
998  False   False          False  False  False
999  False   False          False  False  False

[1000 rows x 5 columns]

In [44]:
csm.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

# so lets take that data to a model

In [46]:
X_train,X_test,y_train,y_test=train_test_split(csm,y,test_size=0.2)

In [47]:
from sklearn.ensemble import RandomForestRegressor

#getting the model
model=RandomForestRegressor()

#fitting the model
model.fit(X_train,y_train)

#checking model or running the model
model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [49]:
#splitting into x and y
X=csm.drop("Price",axis=1)

y=csm["Price"]

In [54]:
print("x")

x


In [56]:
csm

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [52]:
from sklearn.ensemble import RandomForestRegressor

#getting the model
model=RandomForestRegressor()

#fitting the model
model.fit(X_train,y_train)

#checking model or running the model
model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

Lets ignore these errors for good and focus on filling missing datas

In [53]:
csm

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [57]:
csm

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [58]:
#lets work on missing data
carsm=pd.read_csv("car-sales-extended-missing-data.csv")

In [59]:
carsm.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [60]:
#filling the Make
carsm["Make"].fillna("missing",inplace=True)

#filling the Colour
carsm["Colour"].fillna("missing",inplace=True)

#filling the Doors
carsm["Doors"].fillna(4,inplace=True)



In [61]:
#filling the Odometer
carsm["Odometer (KM)"].fillna(carsm["Odometer (KM)"].mean(),inplace=True)

In [63]:
carsm.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

Remove rows with missing price value

In [64]:
carsm.dropna(inplace=True)

In [65]:
carsm.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [66]:
len(carsm)

950

In [67]:
#splitting into x and y
X=carsm.drop("Price",axis=1)

y=carsm["Price"]

In [68]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)],
                             remainder="passthrough")

transformed_X=transformer.fit_transform(carsm)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])